// Test definitions. Do NOT edit this file!
#define CATCH_CONFIG_MAIN // defines main() automatically
#include <iostream>
#include "catch.hpp"
#include "students.hpp"

void printStudent(Student s);
TEST_CASE("Ex1 ", "[example]")
{
	int id;
	string name;
	double score;
	Student student;
	cout << "Enter your ID : ";
	cin >> id;
	cout << "Enter your name: ";
	cin >> name;
	student.setSid(id);
	student.setSname(name);
	for (int i = 0; i < Nscores; i++)
	{
		cout << "Enter your score" << i << "  ";
		cin >> score;
		student.setScores(i, score);
	}
	printStudent(student);
	REQUIRE(student.getSID() == 100001);
	REQUIRE(student.getSname() == "Bill");
}
void printStudent(Student s)
{
	cout << "\nID\t Name\t\t Scores \t\t Sum \t Average \t" << endl;
	cout
		<< s.getSID() << "\t";
	cout << s.getSname() << "\t\t";
	for (int i = 0; i < Nscores; i++)
	{
		cout << s.getScores(i) << "\t";
	}
	cout << s.getSum() << "\t";
	cout << s.getAvg() << "\t";
	cout << endl;
	// REQUIRE(numbers[i] <= numbers[i + 1]);
}